//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkPatterns.Refactoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkPatterns.Refactoring.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items not planned for refactoring cannot use symbols flagged for removal..
        /// </summary>
        internal static string MustNotUsePlannedForRemovalDescription {
            get {
                return ResourceManager.GetString("MustNotUsePlannedForRemovalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; is marked for removal and &apos;{1}&apos; is not marked as needing refactoring by ticket &apos;{2}&apos;.
        /// </summary>
        internal static string MustNotUsePlannedForRemovalMessageFormat {
            get {
                return ResourceManager.GetString("MustNotUsePlannedForRemovalMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not planned for refactoring.
        /// </summary>
        internal static string MustNotUsePlannedForRemovalTitle {
            get {
                return ResourceManager.GetString("MustNotUsePlannedForRemovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items flagged for refactoring should be refactored..
        /// </summary>
        internal static string MustRefactorDescription {
            get {
                return ResourceManager.GetString("MustRefactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; is marked for refactoring and &apos;{1}&apos; is not marked as planned.
        /// </summary>
        internal static string MustRefactorMessageFormat {
            get {
                return ResourceManager.GetString("MustRefactorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is ready for refactor.
        /// </summary>
        internal static string MustRefactorTitle {
            get {
                return ResourceManager.GetString("MustRefactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items ready for removal should be removed..
        /// </summary>
        internal static string ReadyForRemovalDescription {
            get {
                return ResourceManager.GetString("ReadyForRemovalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; is planned for removal and &apos;{1}&apos; is not marked as planned.
        /// </summary>
        internal static string ReadyForRemovalMessageFormat {
            get {
                return ResourceManager.GetString("ReadyForRemovalMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is ready for removal.
        /// </summary>
        internal static string ReadyForRemovalTitle {
            get {
                return ResourceManager.GetString("ReadyForRemovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analyzers version does not support the version of annotations used..
        /// </summary>
        internal static string VersionMismatchDescription {
            get {
                return ResourceManager.GetString("VersionMismatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analyzers version does not support the version of annotations used.
        /// </summary>
        internal static string VersionMismatchMessageFormat {
            get {
                return ResourceManager.GetString("VersionMismatchMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analyzers version does not match the annotations.
        /// </summary>
        internal static string VersionMismatchTitle {
            get {
                return ResourceManager.GetString("VersionMismatchTitle", resourceCulture);
            }
        }
    }
}
